---
- hosts: localhost
  connection: local
  vars:
    option_use: 
    nios_provider:
      host: 192.168.150.46
      username: admin
      password: infoblox

  tasks:

    - name: configure a network ipv4
      nios_network:
        network: 192.168.30.0/24
        comment: ansible created test network
        state: present
        options:
          - name: domain-name
            value: rojaslab.me
#          - name: router
#            value: 192.168.30.1
#            use_option: "{{ option_use | default(omit, true) }}"
        provider: "{{ nios_provider}}"
          
      
